# Generated by Django 4.0.7 on 2022-11-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_registeruser_user_id_alter_registeruser_user_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
