# Generated by Django 4.0.7 on 2022-11-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_registeruser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='user_following',
            field=models.TextField(blank=True),
        ),
    ]
