# Generated by Django 4.0.7 on 2022-11-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_registeruser_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='user_following',
            new_name='followers',
        ),
    ]
