# Generated by Django 4.0.7 on 2022-11-04 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0013_rename_user_following_registeruser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
