# Generated by Django 4.0.7 on 2022-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_registeruser_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='liked_posts',
            field=models.TextField(blank=True),
        ),
    ]
