# Generated by Django 4.0.7 on 2022-11-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_registeruser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Author', 'Author')], default='User', max_length=200),
        ),
    ]
