# Generated by Django 4.1.2 on 2022-11-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
        migrations.AddField(
            model_name='blog',
            name='liked_by_users',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
