# Generated by Django 4.0.7 on 2022-11-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_likes_blog_liked_by_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author_id',
            new_name='author',
        ),
    ]
