# Generated by Django 4.0.7 on 2022-11-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_author_id_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='liked_by_users',
            field=models.TextField(blank=True, default=''),
        ),
    ]
