# Generated by Django 4.1.2 on 2023-03-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Food', 'Food'), ('Travel', 'Travel'), ('Health', 'Health')], default='Technology', max_length=100),
        ),
    ]
